[package]
name = "cross_chain_oracle"
version = "0.1.0"
description = "Created with Anchor"

[lib]
crate-type = ["cdylib"]

[dependencies]
anchor-cli = "0.30.0"
solana-program = "1.8.0"
sha2 = "0.10.8"
